#!/usr/bin/env bash
#
# backfill.sh — one-time COLD-START build of the knowledge base for a fresh (or
# largely unindexed) mirror. Designed to face a ~100-repo first fetch head-on
# without overwhelming any single Claude turn, by splitting the work into stages
# whose fan-in shrinks at every step, and parallelising the wide ones.
#
#   Stage A — provisional, naming-structured STUBS (breadth, light, fast).
#             One light Claude turn PER PROJECT (repos grouped by name prefix)
#             reads only cheap signals — README, file tree, dependency manifest —
#             and writes a provisional stub map per member (+ a provisional project
#             overview). Gives the librarian citeable coverage for every repo long
#             before the deep maps finish. Parallel across projects.
#
#   Stage B — authoritative DEEP MAPS (depth, heavy, parallel).
#             The real per-repo map, generated by digest.sh in maps-only mode,
#             run with bounded concurrency and PRIORITY-ORDERED by last commit so
#             active repos get rich maps first. Resumable: a repo already deep-
#             mapped at its current commit is skipped, so a killed run resumes.
#
#   Stage C — CAPSTONE aggregation (project overviews + cross-project graph).
#             digest.sh in agg-only mode, building the cross-project connections
#             from the project overviews alone (O(projects), never O(repos)).
#
# A lock file (.knowledge/.backfill.lock) marks a run in progress so the steady
# sync loop defers its own digest while this is churning (see loop.sh).
#
# Concurrency defaults to the CPU core count, capped at 10. Override with
# BACKFILL_CONCURRENCY. Uses the machine's logged-in Claude subscription.
#
# Usage:  bash utils/backfill.sh

set -uo pipefail

# This script lives in utils/; the project root is one level up.
UTILS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$UTILS_DIR/.." && pwd)"
REPOS_DIR="$ROOT_DIR/.repositories"
KNOW_DIR="$ROOT_DIR/.knowledge"
DATE="$(date +%F)"
LOCK="$KNOW_DIR/.backfill.lock"

# Project code = repo-name prefix before the first '_' or '-' delimiter.
project_of() { printf '%s\n' "${1%%[_-]*}"; }

# --- Concurrency: CPU cores, capped at 10 (override via BACKFILL_CONCURRENCY) -
detect_cores() {
  if command -v nproc >/dev/null 2>&1; then nproc
  elif [ -r /proc/cpuinfo ]; then grep -c '^processor' /proc/cpuinfo
  else getconf _NPROCESSORS_ONLN 2>/dev/null || echo 4
  fi
}
CONC="${BACKFILL_CONCURRENCY:-$(detect_cores)}"
[ "$CONC" -gt 10 ] && CONC=10
[ "$CONC" -lt 1 ] && CONC=1

# Max repos stubbed per Stage-A turn. Caps how many files a single turn writes so
# a large project (dozens of repos) is split across several bounded turns.
BATCH="${BACKFILL_STUB_BATCH:-12}"
[ "$BATCH" -lt 1 ] && BATCH=1

# How many times to retry a Claude call that fails (rate-limit / transient).
RETRIES="${BACKFILL_RETRIES:-3}"

if ! command -v claude >/dev/null 2>&1; then
  echo "error: the 'claude' CLI is not on PATH." >&2
  exit 1
fi

# Force subscription auth (an API key would switch to metered billing).
unset ANTHROPIC_API_KEY
cd "$ROOT_DIR"
mkdir -p "$KNOW_DIR"

# --- Single-instance lock ----------------------------------------------------
if [ -f "$LOCK" ]; then
  other="$(cat "$LOCK" 2>/dev/null || true)"
  if [ -n "$other" ] && kill -0 "$other" 2>/dev/null; then
    echo "backfill already running (pid $other) — exiting." >&2
    exit 0
  fi
  echo "stale backfill lock (pid ${other:-?}) — taking over." >&2
fi
echo "$$" > "$LOCK"
trap 'rm -f "$LOCK"' EXIT

# --- Bounded-parallel runner: parallel_map MAX func item... ------------------
# Runs `func item` for each item, at most MAX at a time (needs bash >=4.3 wait -n).
parallel_map() {
  local max="$1" func="$2"; shift 2
  local item
  for item in "$@"; do
    "$func" "$item" &
    # Drain below the cap before launching more. `|| true` so a failed job's
    # non-zero status doesn't break the throttle (set -e is off, but be explicit).
    while [ "$(jobs -rp | wc -l)" -ge "$max" ]; do wait -n 2>/dev/null || true; done
  done
  wait
}

# --- Collect the mirrored repos ---------------------------------------------
repos=()
for repo_path in "$REPOS_DIR"/*/; do
  [ -d "${repo_path}.git" ] || continue
  repos+=("$(basename "$repo_path")")
done
if [ "${#repos[@]}" -eq 0 ]; then
  echo "no repositories in the mirror — nothing to backfill."
  exit 0
fi

# Group by project.
declare -A PROJ_MEMBERS
for r in "${repos[@]}"; do
  PROJ_MEMBERS["$(project_of "$r")"]+="$r "
done
projects_total=${#PROJ_MEMBERS[@]}

echo "=============================================================="
echo " cold-start backfill: ${#repos[@]} repos across ${projects_total} projects"
echo " concurrency: ${CONC}   knowledge: ${KNOW_DIR}"
echo "=============================================================="

# A repo still needs a provisional stub if it has no map at all yet.
needs_stub() { [ ! -f "$KNOW_DIR/$1/index.md" ]; }

# Run a Claude turn with retry/backoff (rides out transient rate-limit failures
# from running many turns concurrently). Args: the full claude command.
claude_try() {
  local i=1
  while :; do
    "$@" >/dev/null 2>&1 && return 0
    [ "$i" -ge "$RETRIES" ] && return 1
    sleep $((i * 5)); i=$((i + 1))
  done
}

# ============================================================================
# Stage A — provisional, naming-structured stubs (light; chunked + parallel)
# ============================================================================
# Work is a flat task list so it parallelises evenly and no single turn writes
# too many files: 'stub|<proj>|<repo,repo,...>' (<=BATCH repos) and 'overview|<proj>|'.
echo
echo "### Stage A — provisional stubs (naming-based, light) ###"

stage_a_stubs() {        # $1=project  $2=comma-separated repo names (one chunk)
  local proj="$1" csv="$2"
  local todo=(); IFS=',' read -r -a todo <<< "$csv"
  local stub_list; stub_list="$(printf '%s, ' "${todo[@]}")"
  local multi=""; [ "$(set -- ${PROJ_MEMBERS[$proj]}; echo $#)" -ge 2 ] && multi=1
  local a_uplink=""
  [ -n "$multi" ] && a_uplink="
Then a line: Part of project **${proj}** — [project overview](../${proj}/overview.md)."

  local APROMPT="You are a code librarian doing a FAST first-pass over the '${proj}' project (repositories sharing the '${proj}' name prefix), writing PROVISIONAL stub maps before any deep indexing. Stub these members: ${stub_list}. For EACH, look ONLY at cheap signals under .repositories/<repo>/ — the README (top portion), the top-level file/folder listing (Glob), and any dependency manifest (package.json, pyproject.toml, requirements.txt, go.mod, Cargo.toml, pom.xml). Do NOT read source files deeply; this pass favors speed over depth.

For each member <repo>, write .knowledge/<repo>/index.md beginning EXACTLY with this frontmatter:
---
repo: <repo>
project: ${proj}
indexed: ${DATE}
provisional: true
summary: ONE sentence (max 120 chars) best-guess of what the repo is, from its name and README
---
Then '# <repo>' as an H1 title.${a_uplink}
Then this SHORT body (a stub, not a full map):
## Purpose
1-2 sentences, best guess. Say plainly if uncertain.
## Stack
Languages/frameworks inferred from the manifest and file extensions.
## Naming
Decode the parts of the repo name (project / component / target, split on _ and -) and what each part implies about the repo's role.
## Status
The line: Provisional stub from first fetch — full deep map pending.

Write ONLY the .knowledge/<repo>/index.md files for the members listed above. Mark uncertainty honestly; this is an unverified first guess."

  if claude_try claude -p "$APROMPT" --allowedTools "Read,Grep,Glob,Write"; then
    echo "  ok    stubs ${proj} (${#todo[@]})"
  else
    echo "  FAIL  stubs ${proj}"
  fi
}

stage_a_overview() {     # $1=project — provisional project overview
  local proj="$1"
  local OPROMPT="You are a code librarian writing a PROVISIONAL overview for the '${proj}' project (repositories sharing the '${proj}' name prefix), before deep indexing. Members: $(printf '%s, ' ${PROJ_MEMBERS[$proj]}). Look ONLY at cheap signals (each member's README top and top-level file listing); do NOT read source deeply. Write .knowledge/${proj}/overview.md beginning EXACTLY with:
---
project: ${proj}
built: ${DATE}
provisional: true
summary: ONE sentence (max 120 chars) best-guess of what the ${proj} project does as a whole
---
Then '# ${proj} — project overview (provisional)' as an H1. Then:
## Purpose
1-2 sentences, best guess of how these repos fit together.
## Repos and roles
One bullet per member: '**<repo>** - best-guess role', linking its stub as [map](../<repo>/index.md).
## Status
The line: Provisional — rebuilt from the deep maps once indexing completes.

Write ONLY .knowledge/${proj}/overview.md. Mark uncertainty honestly."

  if claude_try claude -p "$OPROMPT" --allowedTools "Read,Grep,Glob,Write" \
       && [ -f "$KNOW_DIR/$proj/overview.md" ]; then
    echo "  ok    overview ${proj} (provisional)"
  else
    echo "  FAIL  overview ${proj}"
  fi
}

stage_a_worker() {       # $1 = 'stub|proj|csv'  or  'overview|proj|'
  local task="$1" type payload proj
  type="${task%%|*}"; payload="${task#*|}"; proj="${payload%%|*}"; payload="${payload#*|}"
  case "$type" in
    stub)     stage_a_stubs "$proj" "$payload" ;;
    overview) stage_a_overview "$proj" ;;
  esac
}

# Build the task list: chunked stubs for repos still missing a map, plus a
# provisional overview for each multi-repo project that has none yet.
a_tasks=()
for proj in $(printf '%s\n' "${!PROJ_MEMBERS[@]}" | sort); do
  members=(${PROJ_MEMBERS[$proj]})
  todo=(); for m in "${members[@]}"; do needs_stub "$m" && todo+=("$m"); done
  if [ "${#todo[@]}" -gt 0 ]; then
    i=0
    while [ "$i" -lt "${#todo[@]}" ]; do
      chunk=("${todo[@]:$i:$BATCH}")
      csv="$(IFS=','; echo "${chunk[*]}")"
      a_tasks+=("stub|${proj}|${csv}")
      i=$((i + BATCH))
    done
  fi
  if [ "${#members[@]}" -ge 2 ] && [ ! -f "$KNOW_DIR/$proj/overview.md" ]; then
    a_tasks+=("overview|${proj}|")
  fi
done

if [ "${#a_tasks[@]}" -eq 0 ]; then
  echo "  (every repo already has a map — no stubs needed)"
else
  echo "  ${#a_tasks[@]} stub/overview task(s) across ${projects_total} project(s)"
  parallel_map "$CONC" stage_a_worker "${a_tasks[@]}"
fi

# ============================================================================
# Stage B — authoritative deep maps (parallel, priority-ordered by last commit)
# ============================================================================
echo
echo "### Stage B — deep maps (parallel x${CONC}, newest repos first) ###"

# Priority order: most recently committed repos first.
ordered=()
while IFS= read -r r; do [ -n "$r" ] && ordered+=("$r"); done < <(
  for r in "${repos[@]}"; do
    ct="$(git -C "$REPOS_DIR/$r" log -1 --format=%ct 2>/dev/null || echo 0)"
    printf '%s\t%s\n' "$ct" "$r"
  done | sort -rn | cut -f2
)

stage_b_repo() {
  # No --force: digest.sh skips a repo already deep-mapped at its current commit,
  # so a killed/restarted backfill resumes instead of redoing finished work.
  # Retry/backoff rides out transient rate-limit failures under high concurrency.
  local i=1
  while :; do
    if DIGEST_MAPS_ONLY=1 bash "$UTILS_DIR/digest.sh" "$1" >/dev/null 2>&1; then
      echo "  ok    $1"; return 0
    fi
    [ "$i" -ge "$RETRIES" ] && { echo "  FAIL  $1 (after ${RETRIES} tries)"; return 1; }
    sleep $((i * 5)); i=$((i + 1))
  done
}

parallel_map "$CONC" stage_b_repo "${ordered[@]}"

# ============================================================================
# Stage C — capstone: project overviews + cross-project connections + index
# ============================================================================
echo
echo "### Stage C — project overviews + cross-project graph ###"
DIGEST_AGG_ONLY=1 bash "$UTILS_DIR/digest.sh" || true

# --- Report ------------------------------------------------------------------
mapped=0 provisional=0
for r in "${repos[@]}"; do
  f="$KNOW_DIR/$r/index.md"
  [ -f "$f" ] || continue
  if grep -q '^provisional: true$' "$f"; then
    provisional=$((provisional + 1))
  else
    mapped=$((mapped + 1))
  fi
done
echo
echo "=============================================================="
echo " backfill done: ${mapped}/${#repos[@]} deep-mapped, ${provisional} still provisional"
[ "$provisional" -gt 0 ] && echo " (provisional repos will deepen on the next sync loop)"
echo "=============================================================="
